### ISSUE TITLE
Support Email Functionality

### ISSUE THREAD

**Issue by vinoodpersad** [vinoodpersad/COMP231_003-TrustExchange#4]
As an employee, I must be able send a email ticket via Trust Exchange application. This email should go to a custom made Trust Exchange email created by development team for project.

**Comment by whatdadeuce** [comment]
- Add SupportEmailDataAccess in TrustExchangeDAL.Infrastructure.Correspondants
   -package create SMTPClient

- Add SupportEmailModel in TrustExchangeBLL 
   -disposable class to send email to support staff
