### ISSUE TITLE
Create Token Generator for 2 Factor Authentication

### ISSUE THREAD

**Issue by vinoodpersad** [vinoodpersad/COMP231_003-TrustExchange#6]
Program must be created to generate a six digit random code to support 2 factor authentication. This program will communicate with database to save token and send a text message to the respective employee.

**Comment by whatdadeuce** [comment]
- Added token generator and SMS server to send 2FA

1.

**Comment by whatdadeuce** [comment]
1.

**Comment by whatdadeuce** [comment]
**Add Token generator and SMS server to send 2FA** 

1. [Create main Twilio SMS to send text message](https://github.com/vinoodpersad/COMP231_003-TrustExchange_TokenGenerator/commit/f82eaaaad8d75d4c7ff315a5e0ba0a0e3abb7bd7)
2. [Create Server and token generator](https://github.com/vinoodpersad/COMP231_003-TrustExchange_TokenGenerator/commit/cbc5fcfa5325eec8ba14034fb3a1a4f15d1e31be)
3. [Refactor Code and integrate SMS to server](https://github.com/vinoodpersad/COMP231_003-TrustExchange_TokenGenerator/commit/950860fbd2162b0d212bc549ef9c889f1f447044)
